[platformio]
default_envs = gateway_wt32_eth01, gateway_waveshare_s3_eth

[gateway]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
    ESP32Async/AsyncTCP @ 3.5.0
    ESP32Async/ESPAsyncWebServer @ 3.12.0
build_flags =
    -D GATEWAY_FIRMWARE_VERSION=\"0.1.5\"
    -D CORE_DEBUG_LEVEL=0

[env:gateway_wt32_eth01]
extends = gateway
board = wt32-eth01
upload_speed = 115200
build_flags =
    ${gateway.build_flags}
    -D GATEWAY_BOARD_WT32_ETH01

[env:gateway_wt32_eth01_ota]
extends = env:gateway_wt32_eth01
upload_protocol = espota
upload_port = rf-gateway-a0a3b3230e84.local
extra_scripts = pre:scripts/ota_upload.py

[env:gateway_waveshare_s3_eth]
extends = gateway
board = esp32-s3-devkitc1-n16r8
upload_speed = 921600
build_flags =
    ${gateway.build_flags}
    -D GATEWAY_BOARD_WAVESHARE_S3_ETH
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:gateway_waveshare_s3_eth_ota]
extends = env:gateway_waveshare_s3_eth
upload_protocol = espota
upload_port = rf-gateway-a085e3e6cc20.local
extra_scripts = pre:scripts/ota_upload.py
