<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api, errorCode } from '../api/client'
import type { GatewayInfo, GatewaySettings, Health } from '../api/types'
import Icon from '../components/Icon.vue'
import LanguageSelect from '../components/LanguageSelect.vue'
import ThemeToggle from '../components/ThemeToggle.vue'
const info = ref<GatewayInfo | null>(null), health = ref<Health | null>(null), settings = ref<GatewaySettings | null>(null)
const failure = ref(''), saved = ref(false), saving = ref(false), uiVersion = __UI_VERSION__
const form = reactive({ displayName: '', mdnsEnabled: true, ntpEnabled: true, ntpServers: '', pairingSeconds: 120, setupSeconds: 600 })
const byteLength = (value: string) => new TextEncoder().encode(value).length
const servers = computed(() => form.ntpServers.split('\n').map(value => value.trim()).filter(Boolean))
const invalid = computed(() => byteLength(form.displayName) > 48 || servers.value.length > 3 || (form.ntpEnabled && servers.value.length === 0) || servers.value.some(value => value.length > 63 || !/^[A-Za-z0-9.:-]+$/.test(value)) || new Set(servers.value).size !== servers.value.length || form.pairingSeconds < 30 || form.pairingSeconds > 900 || form.setupSeconds < 60 || form.setupSeconds > 1800)
function apply(value: GatewaySettings) { settings.value = value; form.displayName = value.display_name; form.mdnsEnabled = value.mdns_enabled; form.ntpEnabled = value.ntp_enabled; form.ntpServers = value.ntp_servers.join('\n'); form.pairingSeconds = value.pairing_window_seconds; form.setupSeconds = value.setup_window_seconds }
async function save() { if (invalid.value) return; saving.value = true; saved.value = false; failure.value = ''; try { apply(await api.updateSettings({ display_name: form.displayName, mdns_enabled: form.mdnsEnabled, ntp_enabled: form.ntpEnabled, ntp_servers: servers.value, pairing_window_seconds: form.pairingSeconds, setup_window_seconds: form.setupSeconds })); saved.value = true } catch (error) { failure.value = errorCode(error) } finally { saving.value = false } }
onMounted(async () => { const results = await Promise.allSettled([api.info(), api.health(), api.settings()]); if (results[0].status === 'fulfilled') info.value = results[0].value; if (results[1].status === 'fulfilled') health.value = results[1].value; if (results[2].status === 'fulfilled') apply(results[2].value); else failure.value = errorCode(results[2].reason) })
</script>
<template><div class="page"><div class="page-heading"><div><h1>{{ $t('settings.title') }}</h1><p>{{ $t('settings.subtitle') }}</p></div></div><div v-if="failure" class="notice error">{{ $t(`error.${failure}`) }}</div><div v-if="saved" class="notice success">{{ $t('settings.saved') }}</div>
  <form class="settings-grid" @submit.prevent="save">
    <section class="panel settings-card editable"><span class="settings-icon" aria-hidden="true"><Icon name="tune" /></span><div><h2>{{ $t('settings.general') }}</h2><p>{{ $t('settings.generalHint') }}</p><label><span>{{ $t('settings.displayName') }}</span><input v-model="form.displayName" maxlength="48"></label><label class="toggle-row"><input v-model="form.mdnsEnabled" type="checkbox"><span>{{ $t('settings.mdns') }}</span></label></div></section>
    <section class="panel settings-card editable"><span class="settings-icon" aria-hidden="true"><Icon name="clock-outline" /></span><div><h2>{{ $t('settings.time') }}</h2><p>{{ $t('settings.timeHint') }}</p><label class="toggle-row"><input v-model="form.ntpEnabled" type="checkbox"><span>{{ $t('settings.ntp') }}</span></label><label><span>{{ $t('settings.ntpServers') }}</span><textarea v-model="form.ntpServers" rows="3" placeholder="pool.ntp.org"></textarea><small>{{ $t('settings.ntpServersHint') }}</small></label></div></section>
    <section class="panel settings-card editable"><span class="settings-icon" aria-hidden="true"><Icon name="timer-outline" /></span><div><h2>{{ $t('settings.windows') }}</h2><p>{{ $t('settings.windowsHint') }}</p><label><span>{{ $t('settings.pairingSeconds') }}</span><input v-model.number="form.pairingSeconds" type="number" min="30" max="900"></label><label><span>{{ $t('settings.setupSeconds') }}</span><input v-model.number="form.setupSeconds" type="number" min="60" max="1800"></label></div></section>
    <section class="panel settings-card"><span class="settings-icon" aria-hidden="true"><Icon name="update" /></span><div><h2>{{ $t('settings.updates') }}</h2><p>{{ $t('settings.updatesHint') }}</p><dl class="simple-details"><div><dt>{{ $t('status.firmware') }}</dt><dd>{{ info?.firmware_version || health?.firmware || '—' }}</dd></div><div><dt>Web UI</dt><dd>{{ info?.ui.version || uiVersion }}</dd></div><div><dt>{{ $t('status.hostname') }}</dt><dd>{{ info?.hostname || '—' }}</dd></div></dl></div></section>
    <section class="panel settings-card editable"><span class="settings-icon" aria-hidden="true"><Icon name="theme-light-dark" /></span><div><h2>{{ $t('settings.interface') }}</h2><p>{{ $t('settings.interfaceHint') }}</p><div class="pref-row"><span>{{ $t('common.language') }}</span><LanguageSelect /></div><div class="pref-row"><span>{{ $t('theme.label') }}</span><ThemeToggle /></div></div></section>
    <div class="settings-actions"><small v-if="invalid">{{ $t('settings.invalid') }}</small><button class="button primary" :disabled="saving || invalid || !settings" type="submit">{{ saving ? $t('settings.saving') : $t('settings.save') }}</button></div>
  </form>
</div></template>
