[platformio]
default_envs = climate_tmp112

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++17

[node]
platform = atmelmegaavr
board = ATtiny1614
board_build.f_cpu = 8000000L
board_hardware.oscillator = internal
framework = arduino
monitor_speed = 9600
upload_protocol = serialupdi
upload_port = COM6
upload_speed = 115200
lib_extra_dirs = ../shared
lib_deps =
    lowpowerlab/RFM69 @ 1.6.0
build_flags =
    -D NODE_RFM69_FREQUENCY=RF69_868MHZ
    -D NODE_GATEWAY_ID=100
    -D NODE_DEFAULT_POWER_LEVEL=2
    -D NODE_RFM69_CS=PIN_PA4
    -D NODE_RFM69_IRQ=PIN_PA7
    -D NODE_REED_PIN=PIN_PA5
    -D NODE_BUTTON_PIN=PIN_PA6
    -D NODE_INPUT_POLL_PERIOD_MS=250

[env:climate_tmp112]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_CLIMATE_TMP112
    -D NODE_PROFILE_ID=2
    -D NODE_TMP112_ADDRESS=0x48
    -D NODE_CLIMATE_ADAPTIVE_REPORTING
    -D NODE_CLIMATE_CHARGED_REPORT_INTERVAL_MS=60000UL
    -D NODE_CLIMATE_LOW_CHARGE_REPORT_INTERVAL_MS=300000UL
    -D NODE_CLIMATE_LOW_CHARGE_THRESHOLD_MV=2500

[env:climate_tmp112_debug]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_CLIMATE_TMP112
    -D NODE_PROFILE_ID=2
    -D NODE_TMP112_ADDRESS=0x48
    -D NODE_CLIMATE_ADAPTIVE_REPORTING
    -D NODE_CLIMATE_CHARGED_REPORT_INTERVAL_MS=60000UL
    -D NODE_CLIMATE_LOW_CHARGE_REPORT_INTERVAL_MS=300000UL
    -D NODE_CLIMATE_LOW_CHARGE_THRESHOLD_MV=2500
    -D NODE_DEBUG=1
    -D NODE_DEBUG_IDLE_DELAY_MS=50

[env:door]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_DOOR
    -D NODE_PROFILE_ID=5

[env:door_sht40]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_DOOR_SHT40
    -D NODE_PROFILE_ID=7
    -D NODE_SHT40_ADDRESS=0x44

[env:door_tmp112]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_DOOR_TMP112
    -D NODE_PROFILE_ID=8
    -D NODE_TMP112_ADDRESS=0x48

[env:counter_reed]
extends = node
build_flags =
    ${node.build_flags}
    -D NODE_BUILD_COUNTER_REED
    -D NODE_PROFILE_ID=6
