export const en = {
  common: {
    gateway: 'Gateway', uiVersion: 'UI {version}', refresh: 'Refresh', retry: 'Try again', loading: 'Connecting to gateway…', unavailable: 'Unavailable', yes: 'Yes', no: 'No', details: 'Technical diagnostics', healthy: 'Healthy', attention: 'Needs attention', working: 'Working', connected: 'Connected', disconnected: 'Disconnected', synchronized: 'Synchronized', ready: 'Ready', view: 'View', viewAll: 'All nodes', close: 'Close', cancel: 'Cancel', planned: 'Planned', language: 'Language',
  },
  theme: { label: 'Theme', auto: 'Follow system', light: 'Light', dark: 'Dark' },
  time: { underMinute: '< 1 min', minutes: '{value} min', hours: '{value} h', days: '{value} d' },
  nav: { main: 'Main navigation', overview: 'Overview', nodes: 'Nodes', settings: 'Settings' },
  shell: { offline: 'Connection to the gateway was lost. Retrying…', signOut: 'Sign out' },
  login: { title: 'Sign in to the gateway', intro: 'Use the local account created during gateway setup.', username: 'Username', password: 'Password', submit: 'Sign in', signingIn: 'Signing in…' },
  setup: {
    eyebrow: 'First-time setup', title: 'Bring your gateway online', intro: 'Create the first administrator and give this gateway a recognizable name.',
    physicalTitle: 'Physical confirmation required', physicalClosed: 'Briefly press BOOT on the gateway to open the secure setup window.', physicalOpen: 'Setup window is open for {seconds} seconds.',
    username: 'Administrator username', usernameHint: 'Lowercase letters, numbers, dot, dash, or underscore.', password: 'Password', passwordHint: 'Use at least 8 characters.',
    displayName: 'Gateway name', displayPlaceholder: 'Main gateway', advanced: 'Advanced settings', networkId: 'Operational network ID', networkHint: 'Leave empty to generate a secure random ID.',
    submit: 'Configure gateway', saving: 'Configuring…', successTitle: 'Gateway configured', success: 'The administrator account was created and the gateway is ready to use.', continue: 'Go to overview', alreadyConfigured: 'This gateway is already configured', alreadyConfiguredHint: 'Sign in to open the overview and manage the gateway.',
  },
  overview: {
    title: 'Overview', subtitle: 'See whether everything is working and what needs your attention.', attentionTitle: 'Attention needed', nodeAttention: 'Check node “{name}”.', gatewayAttention: 'One of the gateway services is not working correctly.', nodesHint: 'Registered devices and their latest connection', registrySummary: '{count} nodes in the registry', registryUnavailable: 'The detailed list will appear when the secured registry API is implemented.', gateway: 'Gateway', gatewayHint: 'Connection, radio, and system time',
  },
  nodes: {
    title: 'Nodes', subtitle: 'Add devices and see gateway registry and connection state.', add: 'Add node', addFirst: 'Add first node', registered: 'Registered', seen: 'Seen since startup', updates: 'Packets received', unnamed: 'Node {id}', noTelemetry: 'No data', columnName: 'Node', columnFirmware: 'Firmware', columnSignal: 'Signal', columnLastSeen: 'Last seen', columnState: 'State', profile: 'Profile {id}', emptyTitle: 'No nodes yet', emptyHint: 'Add the first sensor or meter to this gateway.', registryUnavailableTitle: 'Registry is not available in the Web UI yet', registryUnavailable: 'This firmware reports only the node count. The detailed `/api/v1/nodes` endpoint is still planned.', deviceUid: 'Device UID', profileLabel: 'Profile', displayName: 'Node name', displayNameHint: '{used} of {max} bytes', displayNameEmpty: 'Left empty, this node shows as “{fallback}”.', save: 'Save name', saving: 'Saving…', delete: 'Remove', deleteConfirm: 'Remove node', deleting: 'Removing…', deleteConfirmTitle: 'Remove “{name}” from the registry?', deleteConfirmHint: 'The gateway forgets this node. The device itself keeps its network credentials and must be factory-reset before it can be paired again.', adminOnly: 'Renaming and removal require an administrator account.', state: { active: 'Online', pending: 'Pending', disabled: 'Disabled' },
  },
  pairing: { title: 'Add a new node', uid: 'Node UID', key: 'Factory key', instructions: 'Click “Add”, then press the node button to connect. You must complete this within the time limit.', active: '{seconds} seconds remaining.', start: 'Add', starting: 'Adding', stop: 'Stop', waiting: 'Press the button on the node now.', scan: 'Scan QR', scanState: { scanning: 'Reading the code…', read: 'Code read. Check the values and press “Add”.', no_code: 'No QR code found in the photo. Try again with the code filling more of the frame.', unsupported: 'This QR code is not a node pairing code.', unreadable: 'This file could not be opened as an image.' } },
  ha: {
    cardHint: 'Readings, history, and automations', notConfigured: 'Not configured', connectTitle: 'Connect Home Assistant', connectHint: 'It only takes a few minutes', configure: 'Configure', title: 'Connect Home Assistant', subtitle: 'All node readings, history, and automations will be available in Home Assistant.', stepTokenTitle: 'Create a connection key', stepTokenHint: 'The gateway will create a read-only key for registry and telemetry access. The key is displayed once.', createToken: 'Create key', creatingToken: 'Creating…', copyToken: 'Copy key', copied: 'Copied', saveToken: 'Save this key now. The gateway cannot display it again.', stepAddTitle: 'Add the integration', stepAddHint: 'In Home Assistant, open Settings → Devices & services → Add integration. Choose RadioSensors and paste the key.', address: 'Gateway address', integration: 'Integration', later: 'Do this later',
  },
  radioReset: { card: 'Radio network', cardHint: 'Network ID and installation key.', action: 'Reset radio network', title: 'Reset the radio network', intro: 'The gateway generates a new installation key and network ID, forgets every registered node, and restarts.', consequence: 'All {count} registered nodes are removed. Each physical node keeps its old credentials and must be factory-reset before it can be paired again. Everyone signed in will have to sign in again.', consequenceEmpty: 'No nodes are registered. Each client signed in will have to sign in again.', networkId: 'Network ID', networkIdHint: 'From 1 to 255. Leave empty to generate one.', confirm: 'Reset and restart', working: 'Resetting…', restarting: 'Gateway is restarting', restartingHint: 'Waiting for it to come back. You will be asked to sign in again.' }, settings: { title: 'Settings', subtitle: 'Core gateway options.', general: 'General', generalHint: 'Gateway name and network discovery.', displayName: 'Gateway name', mdns: 'Enable mDNS discovery', time: 'System time', timeHint: 'UTC synchronization for telemetry timestamps.', ntp: 'Enable NTP', ntpServers: 'NTP servers', ntpServersHint: 'Up to three, one per line.', windows: 'Time windows', windowsHint: 'Duration of temporary operating modes.', pairingSeconds: 'Pairing, seconds (30–900)', setupSeconds: 'Initial setup, seconds (60–1800)', updates: 'Versions', updatesHint: 'Installed firmware and Web UI versions.', interface: 'Interface', interfaceHint: 'Language and theme, stored in this browser only.', save: 'Save settings', saving: 'Saving…', saved: 'Settings saved.', invalid: 'Check the entered values.' },
  status: {
    eyebrow: 'System overview', title: 'Gateway status', subtitle: 'Live health and connectivity at a glance.', updated: 'Updated {time}', autoRefresh: 'automatically every 10 seconds',
    system: 'System', network: 'Ethernet', radio: 'Radio', storage: 'Storage', time: 'Time', telemetry: 'Telemetry', firmware: 'Firmware', board: 'Board', hostname: 'Network name', uptime: 'Uptime', freeHeap: 'Free heap',
    connection: 'Connection', address: 'IP address', mac: 'MAC address', networkId: 'Network', frequency: 'Frequency', signal: 'Last RSSI', encryption: 'Encryption', ready: 'Ready', records: 'Registered nodes', settingsGeneration: 'Settings generation', registryGeneration: 'Registry', lastSync: 'Last sync', nodesSeen: 'Nodes seen', updates: 'Updates', lastNode: 'Last node', state: 'State', timeState: { synchronized: 'Synchronized', synchronizing: 'Synchronizing…', waiting_for_network: 'Waiting for the network', disabled: 'NTP disabled', unknown: 'Unknown' }, apiMismatch: 'This UI expects API v1, but the gateway reports API v{version}.',
  },
  error: {
    invalid_pairing_credentials: 'Enter the 20-hex-character UID and 32-hex-character factory key.',
    pairing_timeout: 'The node did not connect before the window closed. The button on the node may not have been pressed, or the node may be out of range.',
    invalid_display_name: 'The name has more than 48 UTF-8 bytes or contains control characters.', invalid_node_values: 'The node request was not accepted.', node_not_found: 'This node is no longer in the registry.', node_storage_failed: 'The change to the node registry could not be saved.', secrets_locked_by_active_nodes: 'Nodes are still active on the current network.', secrets_storage_failed: 'The new radio secrets could not be saved.', invalid_settings_values: 'Check the settings values.', settings_storage_failed: 'The settings could not be saved.', pairing_unavailable: 'The radio could not enter pairing mode.', admin_required: 'Administrator access is required.', mutation_busy: 'Another change is already in progress.',
    title: 'Could not reach the gateway', generic: 'An unexpected gateway error occurred.', timeout: 'The gateway did not respond in time.', network: 'Check the Ethernet connection and try again.',
    invalid_request: 'The request was not accepted.', invalid_credentials: 'The username or password is incorrect.', authentication_required: 'Sign in to continue.', invalid_csrf_token: 'The session could not authorize this change. Sign in again.', login_busy: 'Another sign-in is being processed. Try again.', session_unavailable: 'A session could not be created.', storage_unavailable: 'Gateway storage is unavailable.', registry_unavailable: 'The node registry is unavailable.', physical_setup_required: 'Press BOOT and submit while the setup window is open.', setup_busy: 'Another setup request is in progress.', setup_already_complete: 'The gateway is already configured.', invalid_setup_values: 'Check the entered values.', invalid_operational_network_id: 'Choose a network ID from 1 to 255.', password_hash_failed: 'The gateway could not secure the password.', setup_storage_failed: 'The gateway could not save the configuration.',
  },
  validation: { required: 'This field is required.', username: 'Enter 1–32 permitted lowercase characters.', password: 'Enter 8–128 UTF-8 bytes.', displayName: 'Use no more than 48 UTF-8 bytes and no control characters.', networkId: 'Enter a number from 1 to 255.' },
}
