export const en = {
  common: {
    gateway: 'Gateway', uiVersion: 'UI {version}', refresh: 'Refresh', retry: 'Try again', loading: 'Connecting to gateway…', unavailable: 'Unavailable', yes: 'Yes', no: 'No', details: 'Technical diagnostics', healthy: 'Healthy', attention: 'Needs attention', working: 'Working', connected: 'Connected', disconnected: 'Disconnected', synchronized: 'Synchronized', ready: 'Ready', view: 'View', viewAll: 'All nodes', close: 'Close', cancel: 'Cancel', planned: 'Planned',
  },
  nav: { main: 'Main navigation', overview: 'Overview', nodes: 'Nodes', settings: 'Settings' },
  shell: { reachable: 'Gateway reachable', unreachable: 'Gateway unavailable', signOut: 'Sign out' },
  login: { title: 'Sign in to the gateway', intro: 'Use the local account created during gateway setup.', username: 'Username', password: 'Password', submit: 'Sign in', signingIn: 'Signing in…' },
  setup: {
    eyebrow: 'First-time setup', title: 'Bring your gateway online', intro: 'Create the first administrator and give this gateway a recognizable name.',
    physicalTitle: 'Physical confirmation required', physicalClosed: 'Briefly press BOOT on the gateway to open the secure setup window.', physicalOpen: 'Setup window is open for {seconds} seconds.',
    username: 'Administrator username', usernameHint: 'Lowercase letters, numbers, dot, dash, or underscore.', password: 'Password', passwordHint: 'Use at least 8 characters.',
    displayName: 'Gateway name', displayPlaceholder: 'Main gateway', advanced: 'Advanced settings', networkId: 'Operational network ID', networkHint: 'Leave empty to generate a secure random ID.',
    submit: 'Configure gateway', saving: 'Configuring…', successTitle: 'Gateway configured', success: 'The administrator was created. You can connect Home Assistant now or do it later.', continue: 'Go to overview', continueHa: 'Connect Home Assistant', skipHa: 'Do this later', alreadyConfigured: 'This gateway is already configured', alreadyConfiguredHint: 'Sign in to open the overview and manage the gateway.',
  },
  overview: {
    title: 'Overview', subtitle: 'See whether everything is working and what needs your attention.', attentionTitle: 'Attention needed', nodeAttention: 'Check node “{name}”.', gatewayAttention: 'One of the gateway services is not working correctly.', nodesHint: 'Registered devices and their latest connection', registrySummary: '{count} nodes in the registry', registryUnavailable: 'The detailed list will appear when the secured registry API is implemented.', gateway: 'Gateway', gatewayHint: 'Connection, radio, and system time',
  },
  nodes: {
    title: 'Nodes', subtitle: 'Add devices and see gateway registry and connection state.', add: 'Add node', addFirst: 'Add first node', registered: 'Registered', seen: 'Seen since startup', updates: 'Packets received', unnamed: 'Node {id}', profile: 'Profile {id}', emptyTitle: 'No nodes yet', emptyHint: 'Add the first sensor or meter to this gateway.', registryUnavailableTitle: 'Registry is not available in the Web UI yet', registryUnavailable: 'This firmware reports only the node count. The detailed `/api/v1/nodes` endpoint is still planned.', state: { active: 'Online', pending: 'Pending', disabled: 'Disabled' },
  },
  pairing: { title: 'Add a new node', intro: 'Enter the node UID and factory key, then start joining on the node.', uid: 'Node UID', uidPlaceholder: '20 hexadecimal characters', uidHint: 'The 10-byte UID; separators may be omitted.', key: 'Factory key', keyPlaceholder: '32 hexadecimal characters', keyHint: 'Used only for this transaction and never persisted.', readyTitle: 'Ready to pair', ready: 'The gateway temporarily switches to the commissioning network after you start.', activeTitle: 'Pairing window is open', active: '{seconds} seconds remaining.', start: 'Start pairing', starting: 'Starting…', stop: 'Stop pairing' },
  ha: {
    cardHint: 'Readings, history, and automations', notConfigured: 'Not configured', connectTitle: 'Connect Home Assistant', connectHint: 'It only takes a few minutes', configure: 'Configure', title: 'Connect Home Assistant', subtitle: 'All node readings, history, and automations will be available in Home Assistant.', stepTokenTitle: 'Create a connection key', stepTokenHint: 'The gateway will create a read-only key for registry and telemetry access. The key is displayed once.', createToken: 'Create key', creatingToken: 'Creating…', copyToken: 'Copy key', copied: 'Copied', saveToken: 'Save this key now. The gateway cannot display it again.', stepAddTitle: 'Add the integration', stepAddHint: 'In Home Assistant, open Settings → Devices & services → Add integration. Choose RadioSensors and paste the key.', address: 'Gateway address', integration: 'Integration', later: 'Do this later',
  },
  settings: { title: 'Settings', subtitle: 'Core gateway options.', general: 'General', generalHint: 'Gateway name and network discovery.', displayName: 'Gateway name', mdns: 'Enable mDNS discovery', time: 'System time', timeHint: 'UTC synchronization for telemetry timestamps.', ntp: 'Enable NTP', ntpServers: 'NTP servers', ntpServersHint: 'Up to three, one per line.', windows: 'Time windows', windowsHint: 'Duration of temporary operating modes.', pairingSeconds: 'Pairing, seconds (30–900)', setupSeconds: 'Initial setup, seconds (60–1800)', updates: 'Versions', updatesHint: 'Installed firmware and Web UI versions.', save: 'Save settings', saving: 'Saving…', saved: 'Settings saved.', invalid: 'Check the entered values.' },
  status: {
    eyebrow: 'System overview', title: 'Gateway status', subtitle: 'Live health and connectivity at a glance.', updated: 'Updated {time}', autoRefresh: 'automatically every 10 seconds',
    system: 'System', network: 'Ethernet', radio: 'Radio', storage: 'Storage', time: 'Time', telemetry: 'Telemetry', firmware: 'Firmware', board: 'Board', hostname: 'Network name', uptime: 'Uptime', freeHeap: 'Free heap',
    connection: 'Connection', address: 'IP address', mac: 'MAC address', networkId: 'Network', frequency: 'Frequency', signal: 'Last RSSI', encryption: 'Encryption', ready: 'Ready', records: 'Registered nodes', settingsGeneration: 'Settings generation', registryGeneration: 'Registry', lastSync: 'Last sync', nodesSeen: 'Nodes seen', updates: 'Updates', lastNode: 'Last node', state: 'State', apiMismatch: 'This UI expects API v1, but the gateway reports API v{version}.',
  },
  error: {
    invalid_pairing_credentials: 'Enter the 20-hex-character UID and 32-hex-character factory key.',
    invalid_settings_values: 'Check the settings values.', settings_storage_failed: 'The settings could not be saved.', pairing_unavailable: 'The radio could not enter pairing mode.', admin_required: 'Administrator access is required.', mutation_busy: 'Another change is already in progress.',
    title: 'Could not reach the gateway', generic: 'An unexpected gateway error occurred.', timeout: 'The gateway did not respond in time.', network: 'Check the Ethernet connection and try again.',
    invalid_request: 'The request was not accepted.', invalid_credentials: 'The username or password is incorrect.', authentication_required: 'Sign in to continue.', invalid_csrf_token: 'The session could not authorize this change. Sign in again.', login_busy: 'Another sign-in is being processed. Try again.', session_unavailable: 'A session could not be created.', storage_unavailable: 'Gateway storage is unavailable.', registry_unavailable: 'The node registry is unavailable.', physical_setup_required: 'Press BOOT and submit while the setup window is open.', setup_busy: 'Another setup request is in progress.', setup_already_complete: 'The gateway is already configured.', invalid_setup_values: 'Check the entered values.', invalid_operational_network_id: 'Choose a network ID from 1 to 255.', password_hash_failed: 'The gateway could not secure the password.', setup_storage_failed: 'The gateway could not save the configuration.',
  },
  validation: { required: 'This field is required.', username: 'Enter 1–32 permitted lowercase characters.', password: 'Enter 8–128 UTF-8 bytes.', displayName: 'Use no more than 48 UTF-8 bytes and no control characters.', networkId: 'Enter a number from 1 to 255.' },
}
