export const uk = {
  common: {
    gateway: 'Шлюз', uiVersion: 'UI {version}', refresh: 'Оновити', retry: 'Спробувати ще', loading: 'З’єднання зі шлюзом…', unavailable: 'Недоступно', yes: 'Так', no: 'Ні', details: 'Технічна діагностика', healthy: 'Справний', attention: 'Потребує уваги', working: 'Працює', connected: 'Підключено', disconnected: 'Немає з’єднання', synchronized: 'Синхронізовано', ready: 'Готове', view: 'Переглянути', viewAll: 'Усі вузли', close: 'Закрити', cancel: 'Скасувати', planned: 'Заплановано',
  },
  nav: { main: 'Головна навігація', overview: 'Огляд', nodes: 'Вузли', settings: 'Налаштування' },
  shell: { reachable: 'Шлюз на зв’язку', unreachable: 'Шлюз недоступний', signOut: 'Вийти' },
  login: { title: 'Вхід до шлюзу', intro: 'Використайте локальний обліковий запис, створений під час налаштування шлюзу.', username: 'Ім’я користувача', password: 'Пароль', submit: 'Увійти', signingIn: 'Вхід…' },
  setup: {
    eyebrow: 'Перше налаштування', title: 'Підготуйте шлюз до роботи', intro: 'Створіть першого адміністратора та дайте шлюзу зрозумілу назву.',
    physicalTitle: 'Потрібне фізичне підтвердження', physicalClosed: 'Коротко натисніть BOOT на шлюзі, щоб відкрити захищене вікно налаштування.', physicalOpen: 'Вікно налаштування відкрите ще {seconds} с.',
    username: 'Ім’я адміністратора', usernameHint: 'Малі латинські літери, цифри, крапка, дефіс або підкреслення.', password: 'Пароль', passwordHint: 'Використайте щонайменше 8 символів.',
    displayName: 'Назва шлюзу', displayPlaceholder: 'Головний шлюз', advanced: 'Розширені параметри', networkId: 'ID робочої мережі', networkHint: 'Залиште порожнім для безпечної випадкової генерації.',
    submit: 'Налаштувати шлюз', saving: 'Налаштування…', successTitle: 'Шлюз налаштовано', success: 'Адміністратора створено. Тепер можна підключити Home Assistant або зробити це пізніше.', continue: 'Перейти до огляду', continueHa: 'Підключити Home Assistant', skipHa: 'Зробити це пізніше', alreadyConfigured: 'Цей шлюз уже налаштовано', alreadyConfiguredHint: 'Увійдіть, щоб перейти до огляду та керування шлюзом.',
  },
  overview: {
    title: 'Огляд', subtitle: 'Чи все працює і які пристрої потребують вашої уваги.', attentionTitle: 'Потрібна увага', nodeAttention: 'Перевірте вузол «{name}».', gatewayAttention: 'Один із сервісів шлюзу працює неправильно.', nodesHint: 'Зареєстровані пристрої та останній зв’язок', registrySummary: 'У реєстрі {count} вузлів', registryUnavailable: 'Детальний список з’явиться після реалізації захищеного API реєстру.', gateway: 'Шлюз', gatewayHint: 'З’єднання, радіо та системний час',
  },
  nodes: {
    title: 'Вузли', subtitle: 'Додавання пристроїв, стан зв’язку та реєстр шлюзу.', add: 'Додати вузол', addFirst: 'Додати перший вузол', registered: 'Зареєстровано', seen: 'Помічено після запуску', updates: 'Пакетів отримано', unnamed: 'Вузол {id}', profile: 'Профіль {id}', emptyTitle: 'Вузлів ще немає', emptyHint: 'Додайте перший сенсор або лічильник до шлюзу.', registryUnavailableTitle: 'Реєстр поки недоступний у Web UI', registryUnavailable: 'Поточна прошивка повідомляє лише кількість вузлів. Детальний endpoint `/api/v1/nodes` ще запланований.', state: { active: 'На зв’язку', pending: 'Очікує', disabled: 'Вимкнено' },
  },
  pairing: { title: 'Додати новий вузол', intro: 'Введіть UID і factory key вузла, а потім запустіть на ньому сполучення.', uid: 'UID вузла', uidPlaceholder: '20 шістнадцяткових символів', uidHint: '10-байтовий UID; розділювачі можна не вводити.', key: 'Factory key', keyPlaceholder: '32 шістнадцяткові символи', keyHint: 'Ключ використовується лише для цієї транзакції і не зберігається.', readyTitle: 'Готово до сполучення', ready: 'Після запуску шлюз тимчасово перейде на commissioning-мережу.', activeTitle: 'Вікно сполучення відкрите', active: 'Залишилося {seconds} с.', start: 'Почати сполучення', starting: 'Запуск…', stop: 'Зупинити сполучення' },
  ha: {
    cardHint: 'Показники, історія та автоматизації', notConfigured: 'Не налаштовано', connectTitle: 'Підключіть Home Assistant', connectHint: 'Це займе кілька хвилин', configure: 'Налаштувати', title: 'Підключіть Home Assistant', subtitle: 'Усі показники вузлів, історія та автоматизації будуть доступні в Home Assistant.', stepTokenTitle: 'Створіть ключ підключення', stepTokenHint: 'Шлюз створить окремий ключ лише для читання реєстру й телеметрії. Ключ буде показано один раз.', createToken: 'Створити ключ', creatingToken: 'Створення…', copyToken: 'Скопіювати ключ', copied: 'Скопійовано', saveToken: 'Збережіть цей ключ зараз. Шлюз більше його не покаже.', stepAddTitle: 'Додайте інтеграцію', stepAddHint: 'У Home Assistant відкрийте Налаштування → Пристрої та служби → Додати інтеграцію. Виберіть RadioSensors і вставте ключ.', address: 'Адреса шлюзу', integration: 'Інтеграція', later: 'Зробити це пізніше',
  },
  settings: { title: 'Налаштування', subtitle: 'Основні параметри шлюзу.', general: 'Основне', generalHint: 'Назва та мережеве виявлення шлюзу.', displayName: 'Назва шлюзу', mdns: 'Увімкнути mDNS discovery', time: 'Системний час', timeHint: 'Синхронізація UTC для timestamp-ів телеметрії.', ntp: 'Увімкнути NTP', ntpServers: 'NTP-сервери', ntpServersHint: 'До трьох, по одному на рядок.', windows: 'Часові вікна', windowsHint: 'Тривалість тимчасових режимів.', pairingSeconds: 'Сполучення, секунди (30–900)', setupSeconds: 'Перше налаштування, секунди (60–1800)', updates: 'Версії', updatesHint: 'Версії прошивки й Web UI.', save: 'Зберегти', saving: 'Збереження…', saved: 'Налаштування збережено.', invalid: 'Перевірте введені значення.' },
  status: {
    eyebrow: 'Огляд системи', title: 'Стан шлюзу', subtitle: 'Актуальний стан і підключення в одному місці.', updated: 'Оновлено {time}', autoRefresh: 'автоматично кожні 10 секунд',
    system: 'Система', network: 'Ethernet', radio: 'Радіо', storage: 'Сховище', time: 'Час', telemetry: 'Телеметрія', firmware: 'Прошивка', board: 'Плата', hostname: 'Мережеве ім’я', uptime: 'Час роботи', freeHeap: 'Вільна пам’ять',
    connection: 'Підключення', address: 'IP-адреса', mac: 'MAC-адреса', networkId: 'Мережа', frequency: 'Частота', signal: 'Останній RSSI', encryption: 'Шифрування', ready: 'Готове', records: 'Зареєстровані вузли', settingsGeneration: 'Покоління налаштувань', registryGeneration: 'Реєстр', lastSync: 'Остання синхронізація', nodesSeen: 'Вузлів помічено', updates: 'Оновлення', lastNode: 'Останній вузол', state: 'Стан', apiMismatch: 'Цей UI очікує API v1, але шлюз повідомляє API v{version}.',
  },
  error: {
    invalid_pairing_credentials: 'Введіть 20 hex-символів UID і 32 hex-символи factory key.',
    invalid_settings_values: 'Перевірте значення налаштувань.', settings_storage_failed: 'Не вдалося зберегти налаштування.', pairing_unavailable: 'Радіо не змогло перейти в режим сполучення.', admin_required: 'Для цієї дії потрібні права адміністратора.', mutation_busy: 'Інша зміна вже виконується.',
    title: 'Не вдалося з’єднатися зі шлюзом', generic: 'Сталася неочікувана помилка шлюзу.', timeout: 'Шлюз не відповів вчасно.', network: 'Перевірте Ethernet-підключення та спробуйте ще.',
    invalid_request: 'Запит не прийнято.', invalid_credentials: 'Неправильне ім’я користувача або пароль.', authentication_required: 'Увійдіть, щоб продовжити.', invalid_csrf_token: 'Сесія не дозволила цю зміну. Увійдіть знову.', login_busy: 'Вже виконується інший вхід. Спробуйте ще раз.', session_unavailable: 'Не вдалося створити сесію.', storage_unavailable: 'Сховище шлюзу недоступне.', registry_unavailable: 'Реєстр вузлів недоступний.', physical_setup_required: 'Натисніть BOOT і надішліть форму, поки вікно налаштування відкрите.', setup_busy: 'Інше налаштування вже виконується.', setup_already_complete: 'Шлюз уже налаштовано.', invalid_setup_values: 'Перевірте введені значення.', invalid_operational_network_id: 'Оберіть ID мережі від 1 до 255.', password_hash_failed: 'Шлюзу не вдалося захистити пароль.', setup_storage_failed: 'Шлюзу не вдалося зберегти конфігурацію.',
  },
  validation: { required: 'Обов’язкове поле.', username: 'Введіть 1–32 дозволених малих латинських символів.', password: 'Введіть 8–128 UTF-8 байтів.', displayName: 'Не більше 48 UTF-8 байтів і без керівних символів.', networkId: 'Введіть число від 1 до 255.' },
}
