; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Default build target
default_envs = node_door_5

[env]
platform = atmelmegaavr
board = ATtiny1614
board_build.f_cpu = 8000000L
board_hardware.oscillator = internal
framework = arduino
monitor_speed = 9600
extra_scripts =
    pre:../../env.py
lib_deps = 
	lowpowerlab/RFM69@^1.5.2
upload_protocol = custom
upload_speed = 57600
upload_flags =
    -d
    tiny1614
    -c
    COM4
    -b
    $UPLOAD_SPEED
upload_command = pyupdi $UPLOAD_FLAGS -f $SOURCE

[env:node_door_5]
build_flags = 
    ;-D RADIO_NODE_DEBUG_LED=PIN_PA5
    ;-D RADIO_NODE_DEBUG_PIN=PIN_PA5
    -D RADIO_NODE_TYPE=21
    -D RADIO_NODE_ID=5
    -D RADIO_GATEWAY_ID=100
    -D RADIO_NETWORK_ID=128
    -D RADIO_POWER_LEVEL=2